# Site settings
title: Postgres Guide
twitter_username: postgresguide
github_username: postgresguide
destination:    ./_site
safe:           false
lsi:            false
include:        [".htaccess"]
exclude:        ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "scss"]
permalink: /:categories/:year/:title
markdown_ext:   markdown,mkd,mkdn,md
markdown: redcarpet

collections:
  setup:
    output: true
  sql:
    output: true
  utilities:
    output: true
  tips:
    output: true
  performance:
    output: true
  sexy:
    output: true
